name: yourappname
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.4.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  anim_search_bar: ^2.0.3
  audio_session: ^0.1.25
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  carousel_indicator: ^1.0.6
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.5.0
  chewie:
    path: packages/chewie/
  country_codes: ^3.3.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  email_validator: ^3.0.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_locales: ^3.0.4
  flutter_otp_text_field: ^1.5.1+1
  flutter_paypal: ^0.2.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^11.4.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.3.0
  gradient_borders: ^1.0.1
  http_auth: ^1.0.4
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0+1
  in_app_purchase_storekit: ^0.3.21
  intl_phone_field: ^3.2.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  miniplayer: ^1.0.1
  onesignal_flutter: ^5.3.0
  package_info_plus: ^8.3.0
  path: ^1.9.0
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  progress_dialog_null_safe: ^3.0.0
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  readmore: ^3.0.0
  responsive_grid_list: ^1.4.0
  rxdart: ^0.28.0
  screen_protector: ^1.4.2+1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.4
  smooth_page_indicator: ^1.2.1
  smooth_star_rating_null_safety: ^1.0.4+2
  subtitle_wrapper_package: ^2.2.1
  text_scroll: ^0.2.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.3
  video_player_web_hls: ^1.3.0
  vimeo_video_player:
    path: packages/vimeo/
  youtube_player_iframe: ^5.2.0

dependency_overrides:
  intl: any
  # package_info_plus: any
  http: any

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appicon/
    - assets/images/
    - assets/
    - assets/videos/
    - assets/locales/en.json
    - assets/locales/ar.json
    - assets/locales/hi.json
    - assets/locales/fr.json
    - assets/locales/gu.json
    - assets/locales/pt.json
    - assets/locales/af.json
    - assets/locales/nl.json
    - assets/locales/de.json
    - assets/locales/id.json
    - assets/locales/es.json
    - assets/locales/tr.json
    - assets/locales/vi.json
    - assets/locales/sq.json
    - assets/videos/splash_video.mp4


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/appicon/appicon.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/appicon/appicon.png"



  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Popins
  #     fonts:
  #       - asset: assets/fonts/Poppins-ExtraLight.ttf
  #   - family: PopinsMedium
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #   - family: Lobster
  #     fonts:
  #       - asset: assets/fonts/LobsterTwo-BoldItalic.ttf
  #   - family: Rubik
  #     fonts:
  #       - asset: assets/fonts/Rubik-Bold.ttf
  #   - family: RubikMedium
  #     fonts:
  #       - asset: assets/fonts/Rubik-Medium.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
